remove deprecated selfLink
open-cluster-management/search-collector pull request #116
Opened 2021-03-22 20:58 UTC by SherinV

**Related Issue:**  open-cluster-management/backlog#10696

### Description of changes

2021-03-22 21:00 UTC, SherinV commented
Do we have to remove the ones in the test-data jsons? https://github.com/open-cluster-management/search-collector/blob/0f4bd03f1ae4e331be89063f753e83826d5c4232/test-data/appdeployable.json#L24

2021-03-22 21:17 UTC, jlpadilla requested changes
Changes are good, but first we need to remove any usage of the `selfLink` field from `search-api`.

2021-03-22 21:28 UTC, SherinV commented
> Changes are good, but first we need to remove any usage of the `selfLink` field from `search-api`.

Yes, facing some issues with committing changes there. The pre-commit hook is failing. Will check that

2021-03-24 17:50 UTC, jlpadilla approved these changes

2021-03-24 18:12 UTC, merged